### ISSUE TITLE
ciscomeraki parser

### ISSUE THREAD

**Issue by jnjkcole** [netwitness/nw-logparsers#15]
The latest Cisco Meraki parser (v20) does not account for several categories of security events. Currently, all of the defined headers are expecting a header that starts with four header fields with a "." between header field 2 and header field 3. Not all syslog messages types begin with this pattern including 

For Meraki MX Security Appliances
- security_event ids_alerted
- security_event security_filtering_file_scanned
- security_event security_filtering_disposition_change

For Meraki MR Access Points
- events rogue SSID detected
- events SSID spoofing detected
- urls HTTP GET requests

Meraki syslog types and logs samples can be found here
https://documentation.meraki.com/zGeneral_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples

Headers
![meraki headers](https://user-images.githubusercontent.com/34521276/37111555-fcbd0e1e-220d-11e8-8d42-42a525325509.PNG)

An example of a header issue
![meraki messages](https://user-images.githubusercontent.com/34521276/37111804-b6a4d816-220e-11e8-82b3-11ab2728e29e.png)

**Comment by manish-rsa** [comment]
Thanks for sharing this, we'll look into this.

**Comment by jnjkcole** [comment]
Thanks!

FYI: Meraki logs can start one of three ways which matches the three highlights I made ( this is just on the MX Security Appliance message types)
1)	GRAY: No timestamp
2)	YELLOW: A default timestamp (which happens to be unix epoch, though it’s not noted)
3)	GREEN: Emblem timestamp (i.e. no year)

![meraki log samples](https://user-images.githubusercontent.com/34521276/37287823-15486128-25dc-11e8-91e8-7fee54aa37b8.png)

Additionally, Meraki has this information about the messages starting with the unix epoch timestamp.

<img width="1031" alt="meraki capture breakdown" src="https://user-images.githubusercontent.com/34521276/37287924-547161ba-25dc-11e8-96fc-5313da599195.png">


And, this is Meraki's response about their message headers in general ... essentially, they can start one of three ways as I mentioned at the top.

<img width="634" alt="rfc5424" src="https://user-images.githubusercontent.com/34521276/37288069-b3921bf8-25dc-11e8-91de-acef310487fa.png">


Regards,
Kevin

**Comment by jnjkcole** [comment]
Additionally, I would advise caution when looking at the published Meraki samples from their website.
See https://documentation.meraki.com/zGeneral_Administration/Monitoring_and_Reporting/Syslog_Event_Types_and_Log_Samples

On looking at their samples more closely, I believe that they have errors and typos in their tables.

**For example, here they have misspelled “flows”**

![1](https://user-images.githubusercontent.com/34521276/37310622-e26c749e-261a-11e8-9b01-8176d415a7db.png)


**Here, I believe they have included part of the output from their syslog collector (Dec 6 08:46:12 192.168.1.1)**

![2](https://user-images.githubusercontent.com/34521276/37310630-e95a34bc-261a-11e8-8bee-b33c40437b8e.png)


**On the MR Access Point table in the “urls” section, they have also included part of a syslog collector message PLUS they have two separate events from two different devices (an MX and an MR) in the message 1) an “events” message about “cellular connection down” from device MX84, and 2) a “urls” message of “request: UNKNOWN” from device MR18.**

![3](https://user-images.githubusercontent.com/34521276/37310635-edf3c4b6-261a-11e8-9a3f-56d73875a823.png)

**Comment by manish-rsa** [comment]
This request is being looked into under ticket SMC-13872.
Thanks for sharing this update with us.
