### ISSUE TITLE
junipervpn (Pulse Secure) parser

### ISSUE THREAD

**Issue by jnjkcole** [netwitness/nw-logparsers#16]
Secure Pulse recently made a change to their syslog format. This has caused the current RSA-provided junipervpn parser (Version 104, updated 2017-12-14 11:40 AM) to stop parsing messages correctly.

SEE: Vendor Knowledge Article: “KB40143 - Syslog format changes in 8.0, 8.1, 8.2 and 8.3”
http://kb.pulsesecure.net/articles/Pulse_Secure_Article/KB40143/

“The string, "Juniper" was removed from the syslog message header and timestamp was added in the correct format in the syslog header.“

**Comment by manish-rsa** [comment]
This request is being looked into under ticket SMC-14020. 
Thanks for sharing this update with us.
